# See https://pre-commit.com for more information
---

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix file endings
      - id: check-added-large-files
        name: Check for large files added
      - id: check-case-conflict
        name: Check for file path case conflicts
      - id: check-executables-have-shebangs
        name: Check that executable files have shebangs
      - id: check-merge-conflict
        name: Check for Git merge conflict detritus
      - id: debug-statements
        name: Check for Python debugger imports and breakpoints

  # Seeding isort's configuration should occur before the invocation of isort.
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
      - id: seed-isort-config
        name: Seed isort config
        args: [--application-directories, src]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        name: isort Python imports
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: Blacken Python

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        name: Flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-logging-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
      - id: mypy
        name: Mypy
        exclude: ^docs/conf.py
